### PR TITLE
saurabh-edited

### PR DESCRIPTION
**Pull request by Saurabh13042004**
# Description

- new file CODEOWNERS uploaded 
- fixed bug

### CODE REVIEW

**Comment by ghost** [comment]
Reviewing this right now, let's see...

**Review by ghost — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Review by Saurabh13042004 — COMMENTED** [review]
removed carl

**Review by ghost — APPROVED** [review]
Approved! Go ahead and merge this PR. Quickly now.

**Comment by Saurabh13042004** [comment]
okay

**Pull request merged**
